#!/usr/bin/env python3
"""Build deterministic train/validation/test splits for Phase 04."""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path
from typing import Any


def load_json(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def read_metadata(path: Path) -> list[dict[str, Any]]:
    with path.open("r", encoding="utf-8", newline="") as f:
        return list(csv.DictReader(f))


def split_name(batch_id: int, fault_label: int, cfg: dict[str, Any]) -> str:
    train_start, train_end = cfg["normal_train_batches"]
    val_start, val_end = cfg["normal_val_batches"]
    test_start, test_end = cfg["normal_test_batches"]
    fault_start, fault_end = cfg["fault_test_batches"]

    if fault_label == 1:
        if fault_start <= batch_id <= fault_end:
            return "test_fault"
        return "holdout_fault_unexpected"
    if train_start <= batch_id <= train_end:
        return "train_normal"
    if val_start <= batch_id <= val_end:
        return "val_normal"
    if test_start <= batch_id <= test_end:
        return "test_normal"
    return "holdout_normal_unexpected"


def write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)


def main() -> None:
    parser = argparse.ArgumentParser(description="Build Phase 04 batch splits")
    parser.add_argument(
        "--metadata",
        default="data/processed/phase04/metadata/batch_metadata.csv",
        help="Batch metadata CSV generated by scripts/04_preprocess_indpensim.py",
    )
    parser.add_argument(
        "--config",
        default="configs/data/split_phase04.json",
        help="Split config JSON",
    )
    parser.add_argument(
        "--output-dir",
        default="data/processed/phase04/splits",
        help="Output split directory",
    )
    args = parser.parse_args()

    project_root = Path.cwd()
    rows = read_metadata(project_root / args.metadata)
    cfg = load_json(project_root / args.config)

    split_rows: list[dict[str, Any]] = []
    counts: dict[str, int] = {}
    for row in rows:
        batch_id = int(float(row["batch_id"]))
        fault_label = int(float(row["fault_label"]))
        split = split_name(batch_id, fault_label, cfg)
        counts[split] = counts.get(split, 0) + 1
        split_rows.append(
            {
                "batch_id": batch_id,
                "fault_label": fault_label,
                "split": split,
                "n_rows": int(float(row["n_rows"])),
                "duration_h": float(row["duration_h"]),
                "process_npz": row["process_npz"],
            }
        )

    forbidden_fault_splits = [
        row for row in split_rows if row["fault_label"] == 1 and row["split"] in {"train_normal", "val_normal"}
    ]
    if forbidden_fault_splits:
        raise RuntimeError(f"Fault batches leaked into train/val: {forbidden_fault_splits}")

    output_dir = project_root / args.output_dir
    output_dir.mkdir(parents=True, exist_ok=True)
    split_csv = output_dir / "batch_splits.csv"
    write_csv(split_csv, split_rows)
    split_json = {
        "schema_version": cfg.get("schema_version", "phase04_v1"),
        "strategy": cfg.get("strategy"),
        "counts": counts,
        "normal_train_batch_ids": [
            row["batch_id"] for row in split_rows if row["split"] == "train_normal"
        ],
        "normal_val_batch_ids": [
            row["batch_id"] for row in split_rows if row["split"] == "val_normal"
        ],
        "normal_test_batch_ids": [
            row["batch_id"] for row in split_rows if row["split"] == "test_normal"
        ],
        "fault_test_batch_ids": [
            row["batch_id"] for row in split_rows if row["split"] == "test_fault"
        ],
        "forbidden": cfg.get("forbidden", []),
        "source_metadata": str(project_root / args.metadata),
    }
    (output_dir / "batch_splits.json").write_text(
        json.dumps(split_json, indent=2, ensure_ascii=False), encoding="utf-8"
    )
    print(json.dumps({"split_csv": str(split_csv), **split_json}, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
